"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";

const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8787";
const WS = process.env.NEXT_PUBLIC_WS_URL || API.replace(/\/+$/, "").replace(/^http/, "ws") + "/ws";
type AnyRecord = Record<string, any>;
const initial: AnyRecord = { model: "convaiinnovations/laya-multilingual", stats: { calls: 0, actions: 0, costUsd: 0 }, snapshot: null, log: [] };
const esc = (x: unknown) => String(x ?? "—");

export default function Home() {
  const [ui,setUi]=useState<AnyRecord>(initial),[socket,setSocket]=useState("connecting"),[notice,setNotice]=useState(""),[command,setCommand]=useState(""),[transcript,setTranscript]=useState(""),[final,setFinal]=useState(true),[mic,setMic]=useState(false),[decision,setDecision]=useState<AnyRecord|null>(null),[candidates,setCandidates]=useState<any[]>([]),[pending,setPending]=useState<any>(null);
  const wsRef=useRef<WebSocket|null>(null),recRef=useRef<any>(null),micRef=useRef(false);
  const send=useCallback((msg:AnyRecord)=>{if(wsRef.current?.readyState!==WebSocket.OPEN){setNotice(`Backend is not connected at ${WS}. Start apps/backend, then wait for “connected” before sending commands.`);return false;}wsRef.current.send(JSON.stringify(msg));setNotice("");return true;},[]);
  useEffect(()=>{let live=true,timer:any;const connect=()=>{if(!live)return;let ws:WebSocket;try{ws=new WebSocket(WS);}catch(err){setSocket("connection error");setNotice(`Could not connect to ${WS}: ${String(err)}`);timer=setTimeout(connect,1500);return;}wsRef.current=ws;ws.onopen=()=>{setSocket("connected");setNotice("");};ws.onclose=(ev)=>{setSocket("reconnecting");setNotice(`Backend WebSocket disconnected (code ${ev.code}). Retrying ${WS}…`);timer=setTimeout(connect,1200);};ws.onerror=()=>{setSocket("connection error");setNotice(`Cannot reach backend WebSocket at ${WS}. Check that apps/backend is running and its port matches this URL.`);ws.close();};ws.onmessage=(ev)=>{try{const {type,payload}=JSON.parse(ev.data);if(type==="hello"){setUi(payload);setNotice("");}if(type==="action")setUi(payload.ui);if(type==="snapshot")setUi((v)=>({...v,snapshot:payload}));if(type==="decision"){setDecision(payload);setUi((v)=>({...v,lastDecision:payload}));}if(type==="transcript"){setTranscript(payload.text);setFinal(payload.final);}if(type==="log")setUi((v)=>({...v,log:[...(v.log||[]),payload].slice(-80)}));if(type==="candidates")setCandidates(payload||[]);if(type==="pending")setPending(payload);if(type==="task")setUi((v)=>({...v,task:payload}));if(type==="tabs")setUi((v)=>({...v,snapshot:v.snapshot?{...v.snapshot,tabs:payload}:v.snapshot}));}catch(err){setNotice(`Received an invalid backend message: ${String(err)}`);}}};connect();return()=>{live=false;clearTimeout(timer);wsRef.current?.close();};},[]);
  const snap=ui.snapshot||{},stats=ui.stats||initial.stats,dec=decision||ui.lastDecision,a=dec?.answers||{},pol=dec?.policy;
  const submit=(e:FormEvent)=>{e.preventDefault();const value=command.trim();if(!value)return;send({type:"command",text:value});setTranscript(value);setFinal(true);setCommand("");};
  const stopMic=()=>{micRef.current=false;try{recRef.current?.stop()}catch{}setMic(false);};
  const startMic=()=>{const SR=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!SR){window.alert("Speech recognition requires Chrome or Edge. You can type a command instead.");return;}const rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang="en-US";rec.maxAlternatives=1;rec.onresult=(ev:any)=>{for(let i=ev.resultIndex;i<ev.results.length;i++){const r=ev.results[i],text=r[0].transcript;setTranscript(text);setFinal(r.isFinal);send({type:"transcript",text,final:r.isFinal,utteranceId:`ui-${Date.now()}-${i}`});}};rec.onerror=(e:any)=>{if(e.error==="not-allowed")stopMic();};rec.onend=()=>{if(micRef.current){try{rec.start()}catch{}}};recRef.current=rec;micRef.current=true;rec.start();setMic(true);};
  const entries=(obj:any)=>Object.entries(obj||{}).sort((x:any,y:any)=>y[1]-x[1]);
  const Bar=({label,value,winner,noul=false}:any)=><div className="grid grid-cols-[minmax(80px,1fr)_2fr_42px] items-center gap-2 py-1 text-xs"><span className="truncate text-slate-400" title={label}>{label}</span><div className="h-2 overflow-hidden rounded-full bg-slate-800"><div className={`h-full rounded-full ${winner?"bg-amber-400":noul?"bg-violet-400":"bg-sky-500"}`} style={{width:`${Math.max(0,Math.min(100,Number(value||0)*100))}%`}}/></div><span className="text-right tabular-nums text-slate-500">{Number(value||0).toFixed(2)}</span></div>;
  const probabilities=(answer:any,labels?:Record<string,string>,max=8,noul=false)=>entries(answer?.probabilities).slice(0,max).map(([key,val]:any)=><Bar key={key} label={labels?.[key]||key} value={val} winner={key===answer?.choice} noul={noul}/>);
  const logs=useMemo(()=>ui.log||[],[ui.log]);
  return <main className="min-h-screen bg-[#080b10] text-slate-100">
    <header className="sticky top-0 z-10 flex flex-wrap items-center gap-3 border-b border-slate-800 bg-[#0b1018]/95 px-5 py-3 backdrop-blur"><div className="mr-2 flex items-center gap-2 font-semibold"><span className="text-amber-400">◉</span> Jev <span className="text-slate-400">Browser Agent</span></div><Pill>MODEL <b>{ui.model||"—"}</b></Pill><Pill>LATENCY <b>{stats.lastLatencyMs??"—"} ms</b> · P50 <b>{stats.p50LatencyMs??"—"} ms</b></Pill><Pill>CALLS <b>{stats.calls||0}</b> · ACTIONS <b>{stats.actions||0}</b></Pill><Pill>COST <b>${Number(stats.costUsd||0).toFixed(6)}</b></Pill><Pill>WORD → ACTION <b>{stats.avgCommandToActionMs??"—"} ms</b></Pill><span className="ml-auto flex items-center gap-2 text-xs text-slate-400"><i className={`h-2 w-2 rounded-full ${socket==="connected"?"bg-emerald-400":socket==="connection error"?"bg-rose-400":"bg-amber-400"}`}/>{socket}</span></header>
    {notice&&<div role="alert" className="border-b border-rose-500/30 bg-rose-950/60 px-5 py-3 text-sm text-rose-200">{notice}</div>}
    <div className="grid gap-4 p-4 xl:grid-cols-[minmax(280px,1fr)_minmax(400px,1.3fr)_minmax(300px,1fr)]">
      <section className="flex min-h-[calc(100vh-90px)] flex-col gap-4"><Card title="Voice control" meta={mic?"LISTENING":"READY"}><div className={`min-h-20 break-words text-2xl font-semibold ${final?"text-slate-100":"text-slate-400"}`}>{transcript||<span className="text-slate-600">Say “go to wikipedia”…</span>}{!final&&<span className="text-slate-500"> …</span>}</div><div className="mt-4 flex flex-wrap gap-2"><button onClick={()=>mic?stopMic():startMic()} className={`rounded-lg px-4 py-2 text-sm font-semibold ${mic?"bg-rose-500/15 text-rose-300 ring-1 ring-rose-500/40":"bg-amber-400 text-black hover:bg-amber-300"}`}>{mic?"Stop microphone":"Start microphone"}</button><button onClick={()=>send({type:"undo"})} className="btn">Undo / back</button><button onClick={()=>send({type:"snapshot"})} className="btn">Re-scan</button></div><form onSubmit={submit} className="mt-3 flex gap-2"><input value={command} onChange={e=>setCommand(e.target.value)} placeholder="Type a command and press Enter" className="min-w-0 flex-1 rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-sm outline-none focus:border-amber-400"/><button className="btn" type="submit">Run</button></form><p className="mt-3 text-xs leading-5 text-slate-500">Speech uses the browser’s Web Speech API in Chrome or Edge. The API key stays in the backend.</p>{pending&&<div className="mt-3 rounded-lg border border-rose-500/30 bg-rose-500/10 p-3 text-sm text-rose-200">Confirmation needed: {pending.summary}. Say “confirm” or “cancel”.</div>}{ui.task&&<div className="mt-3 rounded-lg border border-slate-800 bg-slate-900 p-3 text-xs text-slate-400">Task {ui.task.status} · {ui.task.step}/{ui.task.maxSteps} actions · {ui.task.goal}</div>}{candidates.length>0&&<div className="mt-3 rounded-lg border border-sky-500/30 bg-sky-500/10 p-3 text-sm">Choose a candidate by saying its number: {candidates.map(c=>`${c.n}. ${c.label}`).join(" · ")}</div>}</Card>
      <Card title="Action history" meta={`${logs.length} EVENTS`} grow><div className="space-y-1 overflow-auto font-mono text-xs">{logs.slice().reverse().map((l:any,i:number)=><div key={`${l.t}-${i}`} className="border-b border-slate-800/70 py-1.5"><span className="mr-2 text-slate-600">{new Date(l.t).toLocaleTimeString()}</span><span className={l.level==="error"?"text-rose-300":l.level==="warn"?"text-amber-300":l.level==="act"?"text-emerald-300":"text-slate-400"}>{l.msg}</span></div>)}{!logs.length&&<p className="text-slate-600">Agent events appear here.</p>}</div></Card></section>
      <section className="min-h-[calc(100vh-90px)]"><Card title="Laya decision" meta={dec?`${dec.latencyMs} ms · ${dec.questionCount} QUESTIONS · ${dec.usage?.input_tokens??"?"} TOKENS`:"AWAITING INPUT"} grow><div className={`mb-3 rounded-lg border px-3 py-3 text-lg font-semibold ${pol?.decision==="act"?"border-emerald-500/30 bg-emerald-500/10 text-emerald-300":pol?.decision==="ignore"?"border-slate-700 text-slate-400":"border-amber-500/30 bg-amber-500/10 text-amber-200"}`}>{pol?`${pol.decision.toUpperCase()} — ${pol.summary}`:"Waiting for a voice or text command"}</div><h3 className="section-title">Policy gates</h3><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr>{["Gate","Value","Threshold","Note"].map(x=><th className="border-b border-slate-800 px-2 py-2" key={x}>{x}</th>)}</tr></thead><tbody>{(pol?.reasons||[]).map((r:any,i:number)=><tr key={i}><td className="border-b border-slate-800/70 px-2 py-2">{r.name}</td><td className={`border-b border-slate-800/70 px-2 py-2 ${r.pass?"text-emerald-300":"text-rose-300"}`}>{String(r.value)}</td><td className="border-b border-slate-800/70 px-2 py-2">{String(r.threshold)}</td><td className="border-b border-slate-800/70 px-2 py-2 text-slate-500">{r.note}</td></tr>)}</tbody></table></div><div className="mt-5 grid gap-6 md:grid-cols-2"><div><h3 className="section-title">Intent <span>{a.intent?.confidence!=null?`confidence ${a.intent.confidence.toFixed(2)}`:""}</span></h3>{probabilities(a.intent)}<h3 className="section-title mt-5">Yes / no signals</h3>{["is_command","complete","destructive"].map(k=><Bar key={k} label={k} value={a[k]?.noul} noul/>)}<h3 className="section-title mt-5">Scroll amount</h3>{probabilities(a.scroll_amount,{0:"A little",1:"One page",2:"To the end"})}</div><div><h3 className="section-title">Target element</h3>{probabilities(a.target,Object.fromEntries((snap.elements||[]).map((e:any)=>[e.id,`${e.id} ${e.text||e.placeholder||e.role}`])),6)}<h3 className="section-title mt-5">Site</h3>{probabilities(a.site,undefined,6)}<h3 className="section-title mt-5">Verbatim text / URL spans</h3>{a.text_span&&<><p className="mt-2 text-xs text-slate-500">Text candidates</p>{probabilities(a.text_span,undefined,6)}</>}{a.url_span&&<><p className="mt-2 text-xs text-slate-500">URL candidates</p>{probabilities(a.url_span,undefined,6)}</>}{!a.text_span&&!a.url_span&&<p className="text-xs text-slate-600">No candidates for this command.</p>}</div></div></Card></section>
      <section className="flex min-h-[calc(100vh-90px)] flex-col gap-4"><Card title="Controlled browser" meta={`${snap.tabs?.length||0} TABS`}><dl className="grid grid-cols-[80px_1fr] gap-x-3 gap-y-2 text-xs"><dt className="text-slate-500">URL</dt><dd className="break-all font-mono text-slate-300">{esc(snap.url)}</dd><dt className="text-slate-500">Title</dt><dd>{esc(snap.title)}</dd><dt className="text-slate-500">Site</dt><dd>{esc(snap.site)}</dd><dt className="text-slate-500">Search box</dt><dd className="font-mono">{snap.searchBoxId||"none"}</dd></dl><div className="mt-3 flex gap-1">{(snap.tabs||[]).map((t:any,i:number)=><span key={i} title={t.url} className={`max-w-36 truncate rounded px-2 py-1 text-[11px] ${t.active?"bg-amber-400/15 text-amber-200":"bg-slate-800 text-slate-400"}`}>{t.title||`Tab ${i+1}`}</span>)}</div></Card><Card title="Page elements sent to Laya" meta={`${snap.elements?.length||0} ELEMENTS`} grow><div className="overflow-auto">{(snap.elements||[]).map((el:any)=><div key={el.id} className={`grid grid-cols-[38px_72px_1fr] gap-2 border-b border-slate-800/60 px-2 py-1.5 text-xs ${a.target?.choice===el.id?"bg-amber-400/10":""}`}><span className="font-mono text-amber-300">{el.id}</span><span className="text-slate-500">{el.role}{el.below_fold?" ↓":""}</span><span title={el.href||""} className="truncate text-slate-300">{el.text||el.placeholder||<span className="text-slate-600">(no label)</span>}</span></div>)}{!snap.elements?.length&&<p className="text-sm text-slate-600">Waiting for backend browser snapshot…</p>}</div></Card></section>
    </div>
  </main>;
}
function Pill({children}:any){return <span className="rounded-full border border-slate-800 bg-slate-900 px-2.5 py-1 text-[10px] tracking-wide text-slate-400">{children}</span>}
function Card({title,meta,children,grow}:any){return <section className={`flex min-h-0 flex-col rounded-xl border border-slate-800 bg-[#0d131d] p-4 ${grow?"flex-1":""}`}><div className="mb-3 flex items-center gap-3 text-[11px] font-semibold uppercase tracking-[.14em] text-slate-400"><span>{title}</span>{meta&&<span className="ml-auto truncate text-[10px] font-normal tracking-normal text-slate-600">{meta}</span>}</div>{children}</section>}
